# About/contact
#[author]
name = "Silvano Sallese" # sidebar.html
description = "A passionate <strong>developer and researcher</strong>, learning to be a giant." # sidebar.html
gravatar = "3c2986ad7ac1f2230ea3596f44563328" # md5 hash of your email address # sidebar.html

#[author.contact] # sidebar.html
contact = [
  { name = "linkedin", path = "https://www.linkedin.com/in/lizhihao" },
  { name = "github", path = "https://github.com/codinfox" },
  # { name = "facebook", path = "https://" },
  { name = "twitter", path = "https://twitter.com/Li_Zhihao" },
  { name = "weibo", path = "http://weibo.com/41173780" },
  { name = "email", path = "http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=" }
]
