
# Navigation (2nd level links supported)
# nav = [
#   { name = "Home", path = "/", haschild = false, ischild = false },
#   { name = "Blog", path = "/blog/", haschild = true, ischild = false  },
#   { name = "Categories", path = "/blog/categories/", haschild = false, ischild = true },
#   { name = "Tags", path = "/blog/tags/", haschild = false, ischild = true },
#   { name = "About", path = "/about/", haschild = false, ischild = false },
#   { name = "Github Project", path = "http://svavs.github.io/", haschild = false, ischild = false }
# ]

[[nav]]
name = "Home"
path = "/"

[[nav]]
name = "Blog"
path = "/blog/"
haschild = true

  [[nav.sub]]
  name = "Categories"
  path = "/categories/"

  [[nav.sub]]
  name = "Tags"
  path = "/tags/"

[[nav]]
name = "About"
path = "/about/"

[[nav]]
name = "Github Project"
path = "https://github.com/svavs/codinfox-zola"
